### ISSUE TITLE
RemNote Plugin

### ISSUE THREAD

**Issue by z4151** [remnoteio/remnote-official-plugins#44]
The daily note tab never goes away. Need an option to remove that for efficiency. Thank you.

**Comment by bjsi** [comment]
use this custom css:

```css
div[data-cy="document-sidebar-top-link"][data-label="Today's Note"] {
    display: none;
}
```
